[project]
name = "cpih_json_exporter"
version = "0.1.0"
description = "Fetches ONS MM23 dataset csv, then parses it and generates a hierarchical JSON with CPIH indices and weights"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]